### ISSUE TITLE
Fix Deprecation Warning in calls to numpy.zeros (and maybe elsewhere)

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#208]
Looks like numpy is going to start throwing hard errors if you try to do array stuff with non-integers, e.g.:

/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/imagetools.py:302: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  img = np.zeros(imsz)

We should make sure, at the very least, that calls to np.zeros use integer values throughout the code (and if it's not now, think hard about how to fix it so that it does, e.g., is it just complaining about 12.0 being used, or are we in some places trying to use 12.5).

I've gotten a similar warning in another project about other calls using non-integers, so this might impact other places...

**Comment by cmillion** [comment]
But... I really enjoy misusing the default rounding behavior of numpy operators!

The current behavior of np.zeros() is to always round down. This is the same behavior as np.int(). So we can just wrap the internal variable in np.int(). We should do the same for uses of np.ones().

**Comment by cmillion** [comment]
The imagetools.py example case above was the only place that either np.zeros() or np.ones() could receive a float. I fixed it there by wrapping in np.int() and have pushed to the milestone branch.

**Comment by scfleming** [comment]
I'm still getting this warning on the current v1272 branch:

/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/imagetools.py:302: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  img = np.zeros(imsz)

Was the fix never checked in?  It claims it was, but when I look at imagetools.py I don't see the fix.  I'm going to try to update the existing version on this branch to match the fix 27 days ago...

**Comment by scfleming** [comment]
Unsure what's going on, but the fix for #216 seems to have ruined the fix for this ticket, please examinie again.
